2025-08-13 22:44:21,306 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2025-08-13 22:44:21,307 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Python312\Lib\site-packages\instabot\bot\bot.py
2025-08-13 22:44:21,308 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2025-08-13 22:44:21,873 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2025-08-13 22:44:22,338 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2025-08-13 22:44:22,738 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2025-08-13 22:44:23,172 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2025-08-13 22:44:29,356 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2025-08-13 22:44:29,356 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/ASjogmfYIj1cEX3AOTw1ARCsXE66CkeejDT7n6CfQ8fm1ZZVPTaMBrJ2bw9xRwkIUCibmsc/ASQHR4p9EUy3VK3uDEC9o5GdClCVCx36XnB1VzhqyYk1SiZi6_IgbUrUURB_6MuXQG1Rqcw2_ABrwA/","api_path":"/challenge/ASjogmfYIj1cEX3AOTw1ARCsXE66CkeejDT7n6CfQ8fm1ZZVPTaMBrJ2bw9xRwkIUCibmsc/ASQHR4p9EUy3VK3uDEC9o5GdClCVCx36XnB1VzhqyYk1SiZi6_IgbUrUURB_6MuXQG1Rqcw2_ABrwA/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2025-08-13 22:44:29,356 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2025-08-13 22:44:29,357 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2025-08-13 22:44:29,357 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2025-08-13 22:44:33,402 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2025-08-13 22:44:33,403 - instabot version: 0.117.0 (bot_photo) - INFO - Photo './upload.png' is not uploaded.
2025-08-13 22:44:33,404 - instabot version: 0.117.0 (api) - CRITICAL - Not logged in!
